### PR TITLE
bir baska pr pls do not actually review 

### PR DESCRIPTION
**Pull request by Ece-Kahraman**
## Summary by CodeRabbit

- **Documentation**
	- Updated the README with a new section to improve clarity and provide users with more comprehensive information.

### CODE REVIEW

**Comment by vIremAydin** [comment]
<p>asaSAASASA</p>

**Comment by vIremAydin** [comment]
<p>asaSAASASA</p>

**Comment by vIremAydin** [comment]
<p>EKELSDS</p>

**Comment by vIremAydin** [comment]
<p>ALPER </p>

**Comment by vIremAydin** [comment]
<p>dscdsdcs</p>

**Comment by vIremAydin** [comment]
<p>selam ececim</p>

**Comment by vIremAydin** [comment]
<h1>baslık ekledim dev</h1>

**Comment by vIremAydin** [comment]
<h2>markkk</h2>

**Comment by vIremAydin** [comment]
<p>dhsgkdhjg sd</p>

**Comment by vIremAydin** [comment]
**ACTIVE**: <p>  dd</p>

**Review by AlperMumcular — APPROVED** [review]

**Comment by AlperMumcular** [comment]
> ## markkk

hello

**Review by AlperMumcular — APPROVED** [review]

**Review by AlperMumcular — APPROVED** [review]

**Review by AlperMumcular — APPROVED** [review]

**Review by AlperMumcular — APPROVED** [review]

**Review by AlperMumcular — APPROVED** [review]

**Review by AlperMumcular — APPROVED** [review]

**Pull request merged**
